version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  bffapi:
    container_name: bffApi
    restart: always
    build: ./bff-api/
    ports: 
      - "5000:5000"
    volumes:
      - ./bff-api:/app
    env_file:
      - ./bff-api/.env
    links:
      - mongo
      - colorapi
      
  colorapi:
    container_name: colorApi
    restart: always
    build: ./color-api/
    ports: 
      - "8000:8000"
    volumes:
      - ./color-api:/app
    env_file:
      - ./color-api/.env
    links:
      - mongo
