version: "3.7"
services:
  # colorapi:
  #   container_name: colorApi
  #   restart: always
  #   build: ./color-api/
  #   ports: 
  #     - "8000:8000"
  #   volumes:
  #     - ./color-api:/app
  #   env_file:
  #     - ./color-api/.env
  #   links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
