version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"

  mongo-seed:
    container_name: mongo-seed
    build: ./mongo-seed
    links:
      - mongo

  redis:
    container_name: cache
    image: redis:6.2-rc1-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
         
  bff-api-graphql:
    container_name: bff-api-graphql
    restart: always
    build: ./bff-api-graphql/
    ports: 
      - "5000:5000"
    volumes:
      - ./bff-api-graphql:/app
    env_file:
      - ./bff-api-graphql/.env
    links:
      - mongo
      - colorapi
      - redis

  colorapi:
    container_name: color-api
    restart: always
    build: ./color-api/
    ports: 
      - "8000:8000"
    volumes:
      - ./color-api:/app
    env_file:
      - ./color-api/.env
    links:
      - mongo
